#!/bin/sh

# Exit immediately if a command exits with a non-zero status.
set -e

# Update dependencies
echo "Updating dependencies..."
make go-deps

# Check if fieldalignment is installed, if not, install it
if ! command -v fieldalignment >/dev/null 2>&1; then
  echo "fieldalignment not found, installing..."
  go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest
fi

# Run fieldalignment, if it fails, exit
echo "Running fieldalignment..."
if ! fieldalignment -fix ./...; then
  echo "fieldalignment failed, please run fieldalignment -fix ./... to try to fix the errors"
  exit 1
fi

# Proceed with the commit
echo "Proceeding with the commit..."

