name: Go Test

on:
  push:
    paths:
      - "cmd/**"
      - "internal/**"
      - "pkg/**"
      - "go.mod"
      - "go.sum"
      - "vendor/**"
      - ".github/workflows/unit-test.yml"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"
      - name: Test
        run: make go-test

